#!/usr/bin/env bash
# Display information about subdomains.
# shellcheck disable=SC2086
domain="$1"

resultado () {
    answer=$(dig "$1"".""$domain" | grep -A1 'ANSWER SECTION:' | tr "\t" "\n" | tail -2 | tr "\n" " ") 
    echo "$1 $answer" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then 
    resultado www
    resultado lb-01
    resultado web-01
    resultado web-02
fi
if [ "$#" == 2 ]
then 
    resultado "$2"
fi
