#!/usr/bin/env bash
#   showing numbers from 1 to 100 in list format.
#   showing "FizzBuzz" when the number is a multiple of 3 and 5.
#   showing "Fizz" when the number is a multiple of 3.
#   showing "Buzz" when the number is a multiple of 5.
#   Otherwise, show the number.

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
