#!/usr/bin/env bash
# show the contents of the file `/etc/passwd`.
#  Only show username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
